* $Id: INSTALL.SSL,v 1.3 2005/08/27 16:23:49 jpinto Exp $           *


Note:
The SSL support is working but not tested enough to be proven as stable,
use it at your own risk.
The GNUTLS wrapper is not working, please send me a patch if you find the
problem.

To install with SSL specify the correct configure option:
	./configure --with-ssl=openssl
Then generate your server certificates with:
	make pem
And move them to your ircd etc folder:
	mv *.pem ~/ircd/etc/
